### ISSUE TITLE
Wii new boot2 source code files

### ISSUE THREAD

**Issue by MegaloDawn** [fail0verflow/bootmii#1]
Hello anybody reading this i've found a page on archive.org which has most if not all the files from the 2020 leak with it saying 'Wii and GameCube source code' in one of the files and around May, Wii source code dumps were going out into the wild with it having the IOS source code 
So fail0verflow do you want the link to the page?

**Comment by marcan** [comment]
No,

**Comment by GabubuAvailable** [comment]
lol

**Comment by EpicDoodleboy2** [comment]
![Screenshot_20230207-162449_My Files](https://user-images.githubusercontent.com/111697934/217303993-9c3958f6-ceb4-458f-90bc-dbeff2749fe3.jpg)
![Screenshot_20230207-162454_My Files](https://user-images.githubusercontent.com/111697934/217304002-4fc67e02-639f-40a9-8b57-ea45577889d0.jpg)
![Screenshot_20230206-202312_My Files](https://user-images.githubusercontent.com/111697934/217304005-aa281060-b96e-4fb5-9f61-a580bf6d6d74.jpg)
![Screenshot_20230206-202321_My Files](https://user-images.githubusercontent.com/111697934/217304012-bf001466-6043-4598-8ae7-75d5b4550f6d.jpg)
![Screenshot_20230207-162445_My Files](https://user-images.githubusercontent.com/111697934/217304017-8eb63fa3-5cbe-48ba-ae40-fb7fd1b4347b.jpg)

README
Contents:
block0-n.flash - prewrite block 0
block1-n.flash - prewrite block 1
blocks01.flash - block0, block1 merged into single image
md5sums - md5sums of contents
mios-BOn-062308.bwf - mios bwf file
SD#1-BOn-062308.img - SD card image:
  Offset             Content
  0x000000           sd_final_devel
  0x100000           zeroes
  0x200000           IOS 4
  0x300000           IOS 9
  0x400000           IOS 246
  0x500000           -
  0x600000           Systemmenu
  0xa00000           Compat boot1
  0xb00000           miniIOS

SD#1.log  - Sample log file of messages from ARM JTAG, when
            prewrite procedure is done.

See http://intwww/wiki/index.php/Prewrite/SD_card.

------------------------------

file name is rvl-factory
Well I checked, it has the code with a Linux software patch
This is the last time I'll post something here

**Comment by marcan** [comment]
Well that sure is one way to get yourself banned.
